# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
from math import sqrt
start_limit = 143      # start limit is 143 since we would like to calculate the number after that


def is_pentagonal_number(tep_numb):
    delta_numb = 1 + (24 * tep_numb)
    delta_numb = sqrt(delta_numb)
    if delta_numb.is_integer():
        delta_numb = int(1 + delta_numb)
        if delta_numb % 6 == 0:
            return True
    return False


def check_numbers():
    global start_limit
    while True:
        start_limit += 1
        hex_numb = start_limit * ((2 * start_limit) - 1)
        if is_pentagonal_number(hex_numb):      # we are only checking pentagonal number since hexagonal numbers is a subset of triangle numbers
            print(hex_numb)
            return


check_numbers()
